# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab6ca5961922f64f47767cd96514c5b2ec1c6729296e0c95aa7978d89842d1439232a2b5abb57b8cad774f9f6f5ee40b5a954d5cd301c756f31ffc0ca1173fac

test:
  secret_key_base: 594c560b035f42a7d3e546ebc485584b1d79b1eff32cbd3b460a95fb968e6bdb9e0f026112af26a76fceebca9bd16e68e5f57b913458d778357b864b8a429d17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
